### ISSUE TITLE
Support for Vue project having yarn.lock

### ISSUE THREAD

**Issue by abhijeetj100** [xRealNeon/VuePagesAction#2]
Hi,

I am trying to integrate this action with one of my Vue projects that uses yarn and not npm, so instead of package-lock.json, a yarn.lock is created.

![image](https://user-images.githubusercontent.com/33035102/129636730-48f749ab-4af4-45a3-aa0a-199c526508a3.png)

Is it possible to support that?

Thanks

**PS**: Let me know if this is the wrong place to add this query.

**Comment by xRealNeon** [comment]
Hey👋, sorry for not replying for so long, I have already started to add yarn support. It will probably be ready soon.

**Comment by abhijeetj100** [comment]
Thanks, @xRealNeon.

Looking forward to it 😄

**Comment by xRealNeon** [comment]
Hey, I made the release, please try it out and tell me if it works.

https://github.com/xRealNeon/VuePagesAction/releases/tag/1.0.1

**Comment by xRealNeon** [comment]
You have to add the useyarn option and set it to true @codyatwork 

![grafik](https://user-images.githubusercontent.com/20997346/136907001-53291199-29ef-40a2-bd16-fc738fd1f384.png)
